version: '3.7'
services:
  #####################################
  # RabbitMQ
  #####################################
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_ERLANG_COOKIE: "secret_cookie"
      RABBITMQ_DEFAULT_VHOST: "/"

  #####################################
  # Databases
  #####################################
  employee_service_db:
    image: postgres:alpine
    container_name: employee_service_postgredb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: employeeservice
    ports:
    - "5432:5432"

  event_service_db:
    image: mongo:latest
    container_name: event_service_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: eventservice
    ports:
    - "27017:27017"