spring.profiles.active: ${mode:LOCAL}
server.port: 8083
spring:
  application.name: eventservice
  output.ansi.enabled: ALWAYS

  rabbitmq:
    port: 5672
    host: localhost
    username: rabbitmq
    password: rabbitmq

  data:
    mongodb:
      port: ${database.port}
      host: ${database.host}
      username: ${database.username}
      password: ${database.password}
      database: ${database.dbname}
      authentication-database: admin

logging:
  level:
    root: INFO
    org.spring: DEBUG


amqp:
  exchange-name: employee
  routing-key: employee.message
  queue-name: employee
  concurrent-consumers: 2
  max-concurrent-consumers: 20

config:
  async-enabled: true

---
spring.profiles: LOCAL
database:
  host: localhost
  port: 27017
  username: user
  password: pwd
  dbname: eventservice

logging:
  level:
    root: INFO
    org.spring: DEBUG
    com.takeaway: DEBUG
---
spring.profiles: INTEGRATION
database:
  host: localhost
  port: 27018
  username: user_int
  password: pwd_int
  dbname: employeeevent_Int

logging:
  level:
    root: INFO
    org.spring: DEBUG
    com.takeaway: DEBUG





