spring:
  application.name: eventservice
  output.ansi.enabled: ALWAYS

  rabbitmq:
   port: 5672
   host: localhost
   username: rabbitmq
   password: rabbitmq

  data:
    mongodb:
      port: 27017
      host: localhost
      username: user
      password: pwd
      database: eventservice
      authentication-database: admin

logging:
  level:
    root: INFO
    org.spring: DEBUG

server.port: 8083

amqp:
  exchange-name: employee-exchange
  queue-name: employee-message
  routing-key: employee-message

config:
  async-enabled: true

