spring:
  application.name: eventservice
  output.ansi.enabled: ALWAYS

  rabbitmq:
   port: 5672
   host: localhost
   username: rabbitmq
   password: rabbitmq

server.port: 8083

amqp:
  exchange-name: employee-exchange
  queue-name: employee-message
  routing-key: employee-message

config:
  async-enabled: true

