server.port: 8083

spring.rabbitmq:
  port: 5672
  host: localhost
  username: rabbitmq
  password: rabbitmq

rabbitmq:
  exchange-name: employee-exchange
  queue-name: employee-message
  routing-key: employee-message
