spring.profiles.active: ${mode:LOCAL}
server.port: 8081

spring:
  liquibase:
    change-log: classpath:db/employee-master-changelog.xml
  banner:
    location: classpath:/banner.txt
  application.name: employee-service
  output.ansi.enabled: ALWAYS
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${database.hibernate-mode:validate}
    show-sql: false
    generate-ddl: false
    properties:
      org:
        hibernate:
          envers:
            store_data_at_delete: true
            default_schema: history
            audit_table_suffix: _history
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.dbname}
    username: ${database.username}
    password: ${database.password}

  rabbitmq:
    host: ${rabbitMQ.host}
    port: ${rabbitMQ.port}
    username: ${rabbitMQ.username}
    password: ${rabbitMQ.password}

logging:
  level:
    root: INFO
    org.spring: DEBUG
#     Hibernate SQL Debug output on local profile - want to see the SQL
    org.hibernate.sql: DEBUG
    org.hibernate.SQL: DEBUG
amqp:
  exchange-name: employee
  routing-key: employee.message

---
spring.profiles: LOCAL
database:
  host: localhost
  port: 5432
  username: user
  password: pwd
  dbname: employee

rabbitMQ:
  host: localhost
  port: 5672
  username: rabbitmq
  password: rabbitmq

logging:
  level:
    root: INFO
    org.spring: DEBUG
    de.nexnet: DEBUG
---
spring.profiles: LOCAL_HIBERNATE
spring.profiles.include: LOCAL
spring:
  liquibase:
    enabled: false
database:
  dbname: employee_hibernate
  hibernate-mode: create #alternatively: create-drop
